### PR TITLE
PR for fixing Issues #24 & #16

### PR DESCRIPTION
**Pull request by hmartinez69**
Issues #24 & #16

### CODE REVIEW

**Comment by georg-schwarz** [comment]
Hello Hugo,

thank you very much for your pull request, we appreciate it very much!

We would like to ask you to sign the Contributor License Agreement (see post of CLAassistant in the PR). Unfortunately, we cannot accept your improvements otherwise. If you have any questions on that, you can ask them anytime!

Cheers,
Georg

**Comment by hmartinez69** [comment]
I have already sign CLA

[https://www.asso-hugo.fr/wp-content/uploads/2019/08/unpose_hugo-m_1018_0008-min.jpg]
[facebook]<https://www.facebook.com/asso.hugo/>
[twitter]<https://twitter.com/asso_hugo/>
[linkedin]<https://www.linkedin.com/company/harassers-u-go/>
[instagram]<https://www.instagram.com/asso_hugo/>
Hugo MARTINEZ

Président @ Association HUGO !<https://www.asso-hugo.fr>

Etudiant @ Sup de Pub Lyon<https://www.supdepub.com>

Digital Marketing & PR @ Studio Luuug<https://www.studioluuug.com>

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
06 52 43 97 30<tel:06%2052%2043%2097%2030>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
hugo.martinez@supdepub.com<mailto:hugo.martinez@supdepub.com>
Faire un don à l'association HUGO !<https://www.asso-hugo.fr/faire-un-don/>
Le 2 avr. 2020 à 13:02 +0200, Georg Schwarz <notifications@github.com>, a écrit :

Hello Hugo,

thank you very much for your pull request, we appreciate it very much!

We would like to ask you to sign the Contributor License Agreement (see post of CLAassistant in the PR). Unfortunately, we cannot accept your improvements otherwise. If you have any questions on that, you can ask them anytime!

Cheers,
Georg

**Comment by hmartinez69** [comment]
It’s now ok @georg-schwarz

**Comment by georg-schwarz** [comment]
Perfect, thanks a lot @hmartinez69

**Pull request merged**
